services:
  automad:
    image: automad/automad:v2
    container_name: aokoropi
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    environment:
      - UID=${UID}
    restart: unless-stopped
